% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/exportLabResults.R
\name{Export Lab Results}
\alias{Export Lab Results}
\title{Export Lab Results}
\usage{
exportLabResults(
    results,
    outputFile
)
}
\arguments{
\item{results}{}

\item{outputFile}{}

}
\value{
A workbook
}
\description{
Export Lab Results
}
\details{
Export Lab Results
}
